version: '3.9'
services:
  mysqldb:
    container_name: mysqldbMalek
    image: "mysql:latest"
    restart: "on-failure"
     ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - '/home/mysql-data:/var/lib/mysql'
  spring_app:
    image: "projet:latest"
    container_name: devopsMalek
    restart: "on-failure"
    ports:
      - "8089:8089"
    depends_on:
      - mysqldb
